# Generated by Django 5.2.2 on 2025-06-26 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_status_produto_imagem_produto_localizacao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='preco',
        ),
    ]
