# Generated by Django 5.0.6 on 2025-10-28 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_remove_produto_preco'),
    ]

    operations = [
        migrations.AddField(
            model_name='artista',
            name='curriculo',
            field=models.FileField(default='curriculos_artistas/padrao.pdf', upload_to='curriculos_artistas/'),
        ),
        migrations.AddField(
            model_name='artista',
            name='descricao',
            field=models.TextField(default='Sem descrição disponível.'),
        ),
        migrations.AddField(
            model_name='artista',
            name='foto',
            field=models.ImageField(default='fotos_artistas/padrao.jpg', upload_to='fotos_artistas/'),
        ),
        migrations.AlterField(
            model_name='artista',
            name='nome',
            field=models.CharField(default='Nome não informado', max_length=100),
        ),
    ]
