# Generated by Django 5.0.6 on 2025-10-28 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_artista_curriculo_artista_descricao_artista_foto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artista',
            name='curriculo',
            field=models.FileField(blank=True, null=True, upload_to='curriculos_artistas/'),
        ),
        migrations.AlterField(
            model_name='artista',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='artista',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_artistas/'),
        ),
    ]
